Command: ninja flash
Traceback (most recent call last):
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 1143, in get_security_info
    res = self.check_command(
        "get security info",
    ...<2 lines>...
        resp_data_len=20,
    )
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 565, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 495, in command
    p = self.read()
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 431, in read
    return next(self._slip_reader)
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 1906, in slip_reader
    raise FatalError(msg)
esptool.util.FatalError: Serial data stream stopped: Possible serial noise or corruption.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/__init__.py", line 1173, in _main
    main()
    ~~~~^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/__init__.py", line 1032, in main
    cli(args=args, esp=esp)
    ~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/cli_util.py", line 229, in __call__
    return super().__call__(*args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/rich_click/rich_command.py", line 402, in __call__
    return super().__call__(*args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/rich_click/rich_command.py", line 216, in main
    rv = self.invoke(ctx)
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/__init__.py", line 687, in write_flash_cli
    prepare_esp_object(ctx)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/__init__.py", line 469, in prepare_esp_object
    esp = esp or get_default_connected_device(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        ser_list,
        ^^^^^^^^^
    ...<5 lines>...
        before=ctx.obj["before"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/__init__.py", line 1158, in get_default_connected_device
    _esp.connect(before, connect_attempts)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 821, in connect
    chip_id = self.get_chip_id()
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 1174, in get_chip_id
    chip_id = self.get_security_info()["chip_id"]
              ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 1152, in get_security_info
    res = self.check_command(
        "get security info",
    ...<2 lines>...
        resp_data_len=12,
    )
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 565, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 495, in command
    p = self.read()
  File "/home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/lib/python3.13/site-packages/esptool/loader.py", line 431, in read
    return next(self._slip_reader)
StopIteration

A fatal error occurred: The chip stopped responding.
CMake Error at /home/pseudonymous/esp-idf/components/esptool_py/run_serial_tool.cmake:67 (message):
  
  /home/pseudonymous/.espressif/python_env/idf6.0_py3.13_env/bin/python;;/home/pseudonymous/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed.



